### PR TITLE
Add continuous integration with Travis

### PR DESCRIPTION
**Pull request by EwoutH**
Adds continuous integration with Travis. For optimal integration with GitHub, Travis needs to be [enabled](https://github.com/marketplace/travis-ci) on the GitHub Marketplace.

### CODE REVIEW

**Comment by EwoutH** [comment]
@yoya What do you think?

**Comment by yoya** [comment]
Thank you for your Pull Request !

**Comment by yoya** [comment]
yes.
https://travis-ci.org/yoya/IO_AVIF

**Comment by EwoutH** [comment]
@yoya Thanks for merging! It doesn't look like Travis is enabled yet, did you do that in the GitHub Marketplace??

**Pull request merged**
